export const QUESTIONS = [
  {
    id: 'businessName',
    type: 'text',
    question: 'Apa nama usaha Anda?',
    placeholder: 'Contoh: Dapur Bu Sari, Toko Batik Nusantara...',
  },
  {
    id: 'category',
    type: 'choice',
    question: 'Apa kategori usaha Anda?',
    options: [
      { label: 'Kuliner & Makanan', value: 'kuliner', icon: '🍱' },
      { label: 'Fashion & Pakaian', value: 'fashion', icon: '👗' },
      { label: 'Kerajinan Tangan', value: 'kerajinan', icon: '🧶' },
      { label: 'Kecantikan & Perawatan', value: 'kecantikan', icon: '💄' },
      { label: 'Pertanian & Pangan', value: 'pertanian', icon: '🌿' },
      { label: 'Perdagangan Umum', value: 'perdagangan', icon: '🛍️' },
      { label: 'Jasa & Layanan', value: 'jasa', icon: '🔧' },
      { label: 'Lainnya', value: 'lainnya', icon: '📦' },
    ],
  },
  {
    id: 'businessAge',
    type: 'choice',
    question: 'Sudah berapa lama usaha Anda berdiri?',
    options: [
      { label: 'Kurang dari 1 tahun', value: 'under_1y', icon: '🌱' },
      { label: '1–2 tahun', value: '1y_2y', icon: '📅' },
      { label: '3–5 tahun', value: '3y_5y', icon: '🗓️' },
      { label: 'Lebih dari 5 tahun', value: 'over_5y', icon: '🏆' },
    ],
  },
  {
    id: 'onlinePlatforms',
    type: 'multiselect',
    question: 'Di mana Anda berjualan?',
    hint: 'Boleh pilih lebih dari satu',
    options: [
      { label: 'Shopee', value: 'shopee', icon: '🛒' },
      { label: 'Tokopedia', value: 'tokopedia', icon: '🛒' },
      { label: 'Instagram', value: 'instagram', icon: '📸' },
      { label: 'WhatsApp', value: 'whatsapp', icon: '💬' },
      { label: 'Toko fisik', value: 'toko_fisik', icon: '🏪' },
      { label: 'Facebook', value: 'facebook', icon: '📘' },
      { label: 'TikTok Shop', value: 'tiktok', icon: '🎵' },
      { label: 'Lainnya', value: 'lainnya', icon: '🌐' },
    ],
  },
  {
    id: 'employees',
    type: 'choice',
    question: 'Berapa jumlah karyawan Anda?',
    options: [
      { label: 'Hanya saya sendiri', value: '1', icon: '👤' },
      { label: '1–3 orang', value: '1_3', icon: '👥' },
      { label: '4–10 orang', value: '4_10', icon: '👨‍👩‍👧' },
      { label: 'Lebih dari 10 orang', value: 'over_10', icon: '🏭' },
    ],
  },
  {
    id: 'operationalDays',
    type: 'choice',
    question: 'Berapa hari dalam seminggu usaha Anda beroperasi?',
    options: [
      { label: '1–3 hari', value: '1_3d', icon: '📆' },
      { label: '4–5 hari', value: '4_5d', icon: '📅' },
      { label: '6 hari', value: '6d', icon: '🕐' },
      { label: '7 hari (setiap hari)', value: '7d', icon: '🌟' },
    ],
  },
  {
    id: 'updateFrequency',
    type: 'choice',
    question: 'Seberapa sering Anda memperbarui produk atau layanan?',
    options: [
      { label: 'Jarang (kurang dari sebulan sekali)', value: 'rarely', icon: '😴' },
      { label: 'Kadang (1–2 kali sebulan)', value: 'sometimes', icon: '📆' },
      { label: 'Rutin (setiap minggu)', value: 'weekly', icon: '📅' },
      { label: 'Sangat rutin (hampir setiap hari)', value: 'daily', icon: '📲' },
    ],
  },
  {
    id: 'productDiversity',
    type: 'choice',
    question: 'Apakah Anda memiliki lebih dari satu jenis produk atau layanan?',
    options: [
      { label: 'Tidak, hanya satu produk/layanan', value: 'single', icon: '1️⃣' },
      { label: 'Ya, 2–5 jenis', value: '2_5', icon: '🔢' },
      { label: 'Ya, lebih dari 5 jenis', value: 'over_5', icon: '🎯' },
    ],
  },
];

export const CATEGORIES = {
  kuliner: 'Kuliner & Makanan',
  fashion: 'Fashion & Pakaian',
  kerajinan: 'Kerajinan Tangan',
  kecantikan: 'Kecantikan & Perawatan',
  pertanian: 'Pertanian & Pangan',
  perdagangan: 'Perdagangan Umum',
  jasa: 'Jasa & Layanan',
  lainnya: 'Lainnya',
};

export const RATING_LABELS = {
  A: {
    label: 'A',
    range: '85 – 100',
    title: 'Sangat Layak',
    description: 'Usaha Anda memiliki profil kredit yang sangat kuat. Peluang mendapat pembiayaan sangat besar.',
    color: 'text-green-600',
    bg: 'bg-green-50',
    border: 'border-green-200',
  },
  B: {
    label: 'B',
    range: '70 – 84',
    title: 'Layak',
    description: 'Profil usaha Anda sudah baik. Ada beberapa area kecil yang bisa diperkuat untuk meningkatkan peluang.',
    color: 'text-green-500',
    bg: 'bg-green-50',
    border: 'border-green-100',
  },
  C: {
    label: 'C',
    range: '55 – 69',
    title: 'Cukup Layak',
    description: 'Usaha Anda berpotensi, namun perlu penguatan di beberapa dimensi sebelum mengajukan pembiayaan besar.',
    color: 'text-yellow-600',
    bg: 'bg-yellow-50',
    border: 'border-yellow-200',
  },
  D: {
    label: 'D',
    range: '40 – 54',
    title: 'Perlu Perhatian',
    description: 'Ada beberapa tantangan yang perlu diatasi. Kami punya rekomendasi langkah konkret untuk Anda.',
    color: 'text-orange-600',
    bg: 'bg-orange-50',
    border: 'border-orange-200',
  },
  E: {
    label: 'E',
    range: '0 – 39',
    title: 'Perlu Pengembangan',
    description: 'Usaha Anda masih dalam tahap awal. Fokus dulu pada memperkuat fondasi sebelum mencari pembiayaan.',
    color: 'text-red-600',
    bg: 'bg-red-50',
    border: 'border-red-200',
  },
};

export const LENDER_RECOMMENDATIONS = [
  {
    id: 'kur_bri',
    name: 'KUR BRI (Kredit Usaha Rakyat)',
    logo: '🏦',
    type: 'Bank Pemerintah',
    minRating: 'C',
    plafon: 'Rp 1 juta – Rp 500 juta',
    bunga: '6% per tahun',
    syarat: 'Usaha min. 6 bulan, KTP, tidak sedang kredit macet',
    keunggulan: 'Bunga rendah, jaringan luas, bisa tanpa agunan s.d. Rp 100 juta',
    link: 'https://bri.co.id/kur',
  },
  {
    id: 'mekar',
    name: 'Mekar.id',
    logo: '🌱',
    type: 'P2P Lending (OJK)',
    minRating: 'D',
    plafon: 'Rp 500 ribu – Rp 50 juta',
    bunga: '12 – 24% per tahun',
    syarat: 'KTP, foto usaha, minimal 3 bulan berjalan',
    keunggulan: 'Proses online penuh, cepat cair, cocok untuk UMKM pemula',
    link: 'https://mekar.id',
  },
  {
    id: 'kredit_pintar',
    name: 'Kredit Pintar',
    logo: '⚡',
    type: 'Fintech Lending (OJK)',
    minRating: 'D',
    plafon: 'Rp 600 ribu – Rp 20 juta',
    bunga: '1.5 – 2% per bulan',
    syarat: 'KTP, selfie, isi formulir online',
    keunggulan: 'Tanpa agunan, cair dalam 24 jam, proses 100% digital',
    link: 'https://kreditpintar.com',
  },
  {
    id: 'koperasi',
    name: 'Koperasi Simpan Pinjam Lokal',
    logo: '🤝',
    type: 'Koperasi',
    minRating: 'E',
    plafon: 'Rp 500 ribu – Rp 25 juta',
    bunga: '1 – 2% per bulan',
    syarat: 'Menjadi anggota koperasi, KTP, simpanan pokok',
    keunggulan: 'Fleksibel, berbasis komunitas, mendukung ekonomi lokal',
    link: null,
  },
];
